### ISSUE TITLE
Ring of Evershield Breaks Clicking on Character

### ISSUE THREAD

**Issue by underdevelopedhuman** [TheSparhawk/SparsSorcerousSundries#2]
Ring of Evershield causes the user's model to be unclickable, failing to start a conversation with said character. Also spells cannot target them unless the portrait is used for targeting.

**Comment by Xideta** [comment]
Still an active issue, means you shouldn't give it to any companion.

**Comment by TheSparhawk** [comment]
I have not been able to replicate this, will look into it again and try and fix with the next dlc drop.

**Comment by TheSparhawk** [comment]
Next version has a fix now. Will upload soon tm.
