### ISSUE TITLE
Game will not load with this installed after last update

### ISSUE THREAD

**Issue by DanZinagri** [TheSparhawk/SparsSorcerousSundries#6]
I hadn't tried with the last couple updates, but as the new DLC dropped today i decided to boot this back up, but the game would get stuck at the loading bar before the main menu.

I went 1 at a time with my mods to see why it couldn't get past the loading bar and narrowed it down to this one.

**Comment by NosVladimir** [comment]
Can confirm. Also any previous saves with this mod enabled cannot be loaded. Hope there will be a fix soon

**Comment by NosVladimir** [comment]
Update: looks like there has already been a version update for this mod. The author seems to have forgotten to update the realease page, but I was able to download the source code and drag the zip file included there into UMM/ModFinder. Now I can load my previous saves and there doesn't seem to have any bugs at the moment

**Comment by ManweTheValar** [comment]
Hello my previous save games will not load. When I reinstalled this mod seizes up on the load screen.
